# digest.ps1
# PHASE 4: DIGEST - Analysis & Planning Helper

param(
    [string]$AppDirName = "maieutic-app",
    [string]$RootPath = "."
)

$ErrorActionPreference = "Stop"

try {
    $maieuticApp = Join-Path $RootPath $AppDirName
    $scratchDir = Join-Path $maieuticApp "scratch"
    $planFile = Join-Path $scratchDir "DIGESTION_PLAN.md"

    Write-Host "[INFILTRATE] Starting Digestion Analysis..." -ForegroundColor Cyan
    Write-Host "Target Scratch: $scratchDir" -ForegroundColor Gray

    if (-not (Test-Path $scratchDir)) {
        Throw "Scratch directory not found at $scratchDir. Did you run Phase 1 & 2?"
    }

    $files = Get-ChildItem -Path $scratchDir -Recurse -File

    $sb = [System.Text.StringBuilder]::new()
    $sb.AppendLine("# DIGESTION PLAN") | Out-Null
    $sb.AppendLine("Generated by digest.ps1. This plan maps legacy files to the Maieutic structure.") | Out-Null
    $sb.AppendLine("Action Required: Agent/User must review and execute moves.") | Out-Null
    $sb.AppendLine("") | Out-Null
    $sb.AppendLine("| Original Path | Proposed Destination | Type | Notes |") | Out-Null
    $sb.AppendLine("|---|---|---|---|") | Out-Null

    foreach ($f in $files) {
        $relPath = $f.FullName.Replace($scratchDir, "").Trim("\")
        
        # Default Destination: encapsulate in a project named 'Legacy'
        $dest = "projects\Legacy\$relPath" 
        
        $type = $f.Extension.ToLower()

        # Heuristics for smarter sorting
        if ($relPath -match "^docs\\") { 
            # Preserve docs folder structure but move to docs/legacy
            $dest = "docs\legacy\$relPath" 
        }
        elseif ($relPath -match "^tests\\") { 
            $dest = "tests\legacy\$relPath" 
        }
        elseif ($type -eq ".py" -and $relPath -notmatch "setup.py") {
            # Maybe it's a script? 
        }
        elseif ($relPath -eq "requirements.txt") {
            $dest = "config\requirements_legacy.txt"
        }
        elseif ($relPath -eq "README.md") {
            $dest = "docs\legacy\README_ORIGINAL.md"
        }

        $sb.AppendLine("| $relPath | $dest | $type | Pending Review |") | Out-Null
    }

    if (-not (Test-Path $planFile)) {
        New-Item -Path $planFile -ItemType File -Force | Out-Null
    }
    Set-Content -Path $planFile -Value $sb.ToString()
    
    Write-Host "[SUCCESS] Digestion Plan created at $planFile" -ForegroundColor Green
    Write-Host "Next Step: Run the Agent to execute the migration based on this plan."

}
catch {
    Write-Error "Digestion Failed: $($_.Exception.Message)"
}
